### ISSUE TITLE
Not displayed on the desktop version

### ISSUE THREAD

**Issue by jekeam** [harshil21/TGDates#4]
Not displayed on desktop version, mobile version is fine:
![image](https://github.com/harshil21/TGDates/assets/19660852/187eb4db-8d91-43fd-b1fe-b3cec7d86a4a)
version 4.8.3 x64: https://github.com/telegramdesktop/tdesktop/tree/v4.8.3

**Comment by harshil21** [comment]
![image](https://github.com/harshil21/TGDates/assets/37377066/bc620de0-c18a-4397-b909-7f87f4cfd9fc)

It works fine for me on TDesktop 4.8.7 (beta), Linux. 
Can you update your version and tell me which OS it is?

If it doesn't work after updating, can you:
1) Try if https://t.me/DurgerKingBot 's webview works
2) Enable inspect element (Settings > Advanced > Experimental Settings > Enable webview inspecting) and try inspecting element and seeing the console logs?

**Comment by jekeam** [comment]
The webview inspecting function does not work for me, the menu does not open as it should be "Right click in the WebView and choose Inspect.", despite its activation. Updates are successful, I also tried to install a portable clean version and it did not help. OS win pro 10 22H2

**Comment by jekeam** [comment]
You can close the ticket, because data is not enough to solve the problem...

**Comment by jekeam** [comment]
There is a long load, I suspect that I am clouded in access to servers due to the fact that I am from Russia.

**Comment by harshil21** [comment]
but does the DurgerKing bot webview work for you?

**Comment by jekeam** [comment]
> but does the DurgerKing bot webview work for you?

Yes, like other bots on the webapp - which I used

**Comment by jekeam** [comment]
> but does the DurgerKing bot webview work for you?

I checked on my second laptop and it works there. There is the same version and the same OS, but there are no problems.

**Comment by jekeam** [comment]
Intereno but the debug menu works there (by pressing the right mouse button)

**Comment by harshil21** [comment]
okay, I will investigate when I have the time

**Comment by jekeam** [comment]
> okay, I will investigate when I have the time
It looks like I either have a broken Windows or block the antivirus, when I run it as administrator, I generally get an error on any webapp, example:
![image](https://github.com/harshil21/TGDates/assets/19660852/58dab5e6-bec2-44b7-8565-04a62580734d)

**Comment by jekeam** [comment]
I had a broken inline Edge browser - this turned out to be the problem.
